{"name": "Login con credenciales incorrectas -- @1.2 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643925623858, "stop": 1643925626453}, {"name": "When se lanza el login con \"badUser1\" y \"badPa123ss\"", "status": "passed", "start": 1643925626454, "stop": 1643925626797}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "start": 1643925626798, "stop": 1643925626822}], "parameters": [{"name": "usuario", "value": "badUser1"}, {"name": "contrasena", "value": "badPa123ss"}, {"name": "elemento", "value": "error"}], "start": 1643925623856, "stop": 1643925626878, "uuid": "2c3810af-cd5f-4041-b655-b8370209c81d", "historyId": "b8160f46be5c58db8aa09ffbb8a9fc7b", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}