{"name": "Login con credenciales incorrectas -- @1.1 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643925620012, "stop": 1643925623394}, {"name": "When se lanza el login con \"badUser\" y \"badPass\"", "status": "passed", "start": 1643925623395, "stop": 1643925623766}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "start": 1643925623767, "stop": 1643925623790}], "parameters": [{"name": "usuario", "value": "badUser"}, {"name": "contrasena", "value": "badPass"}, {"name": "elemento", "value": "error"}], "start": 1643925620011, "stop": 1643925623853, "uuid": "1a42b29e-54ba-4cc2-af17-f3277f6b26d0", "historyId": "421b9d06fcb7e9259464069b6fbc1ec0", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}