{"name": "Login con credenciales incorrectas -- @1.1 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643925108493, "stop": 1643925112462}, {"name": "When se lanza el login con \"badUser\" y \"badPass\"", "status": "passed", "start": 1643925112463, "stop": 1643925112904}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "start": 1643925112905, "stop": 1643925112930}], "parameters": [{"name": "usuario", "value": "badUser"}, {"name": "contrasena", "value": "badPass"}, {"name": "elemento", "value": "error"}], "start": 1643925108492, "stop": 1643925112988, "uuid": "a9b06a60-b22f-4f9d-82ec-1d20e3286d1c", "historyId": "421b9d06fcb7e9259464069b6fbc1ec0", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}